# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "a56c0b927e6465d37cae3e97d35d4d18ab2b96cd"  # frozen: v0.16.9
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: "2aeb804518b4373dbf5adb8dddc5466d9a6e6b21"  # frozen: 0.12.19
    hooks:
      - id: uv-lock
