[tox]
envlist = py{3.9,3.10,3.11}-pytest{8.0,8.1,8.2,8.3,latest}-gherkin_official{29,30,32,33,34,35,36,37,latest}-coverage
          py{3.12,3.13,3.14}-pytest{8.0,8.1,8.2,8.3,latest}-gherkin_official{29,30,32,33,34,35,36,37,latest}-coverage
          py3.12-pytestlatest-xdist-coverage
          mypy

[testenv]
parallel_show_output = true
setenv =
    coverage: _PYTEST_CMD=coverage run -m pytest
    xdist: _PYTEST_MORE_ARGS=-n3 -rfsxX
deps =
    gherkin_officiallatest: gherkin-official
    gherkin_official37: gherkin-official~=37.0.0
    gherkin_official36: gherkin-official~=36.0.0
    gherkin_official35: gherkin-official~=35.0.0
    gherkin_official34: gherkin-official~=34.0.0
    gherkin_official33: gherkin-official~=33.0.0
    gherkin_official32: gherkin-official~=32.0.0
    gherkin_official30: gherkin-official~=30.0.0
    gherkin_official29: gherkin-official~=29.0.0

    pytestlatest: pytest
    pytest8.1: pytest~=8.1.0
    pytest8.0: pytest~=8.0.0

    coverage: coverage[toml]
    xdist: pytest-xdist
commands = {env:_PYTEST_CMD:pytest} {env:_PYTEST_MORE_ARGS:} {posargs:-vvl}

[testenv:mypy]
deps =
  poetry==2.0.0
  poetry-plugin-export
allowlist_externals = sh
commands_pre =
    sh -c "\
      poetry export --only=dev --format requirements.txt > requirements.txt && \
      pip install -r requirements.txt && \
      :"
commands = mypy
