import sys

try:
    from types import ModuleType
except ImportError:
    ModuleType = type(sys)

from _pytest.python import Module
from .scenario import scenarios


class PytestBDDModule(Module):
    """
    Class that represents *.feature file as python module
    """

    def _getobj(self):
        # Add _test suffix to module name
        module_name = self.nodeid.replace("/", ".").rsplit(".", 1)[0] + "_test"

        # Create dummy module to store tests
        module = ModuleType(
            name=module_name, doc="Autogenerated python module for {!r} feature file".format(str(self.fspath))
        )
        sys.modules[module_name] = module

        # Add scenarios for dummy module
        scenarios(self.fspath.basename, features_base_dir=self.fspath.dirname, module=module)

        return module
