from pathlib import Path

from src.pytest_bdd.gherkin_parser import (
    Background,
    Cell,
    Child,
    Comment,
    DataTable,
    DocString,
    ExamplesTable,
    Feature,
    GherkinDocument,
    Location,
    Row,
    Rule,
    Scenario,
    Step,
    Tag,
    get_gherkin_document,
)


def test_parser():
    test_dir = Path(__file__).parent
    feature_file = test_dir / "test.feature"
    feature_file_path = str(feature_file.resolve())

    # Call the function to parse the Gherkin document
    gherkin_doc = get_gherkin_document(feature_file_path)

    # Define the expected structure
    expected_document = GherkinDocument(
        feature=Feature(
            keyword="Feature",
            _location=Location(column=1, line=2),
            tags=[],
            name="User login",
            description="  As a registered user\n  I want to be able to log in\n  So that I can access my account",
            children=[
                Child(
                    background=Background(
                        _id="1",
                        keyword="Background",
                        _location=Location(column=3, line=8),
                        name="",
                        description="",
                        steps=[
                            Step(
                                _id="0",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=10),
                                text="the login page is open",
                                data_table=None,
                                doc_string=None,
                            )
                        ],
                    ),
                    rule=None,
                    scenario=None,
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="6",
                        keyword="Scenario",
                        _location=Location(column=3, line=13),
                        name="Successful login with valid credentials",
                        description="",
                        steps=[
                            Step(
                                _id="2",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=14),
                                text="the user enters a valid username",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="3",
                                keyword="And",
                                keyword_type="Conjunction",
                                _location=Location(column=5, line=15),
                                text="the user enters a valid password",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="4",
                                keyword="When",
                                keyword_type="Action",
                                _location=Location(column=5, line=16),
                                text="the user clicks the login button",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="5",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=17),
                                text="the user should see the dashboard",
                                data_table=None,
                                doc_string=None,
                            ),
                        ],
                        tags=[],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="15",
                        keyword="Scenario Outline",
                        _location=Location(column=3, line=19),
                        name="Unsuccessful login with invalid credentials",
                        description="",
                        steps=[
                            Step(
                                _id="7",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=20),
                                text='the user enters "<username>" as username',
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="8",
                                keyword="And",
                                keyword_type="Conjunction",
                                _location=Location(column=5, line=21),
                                text='the user enters "<password>" as password',
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="9",
                                keyword="When",
                                keyword_type="Action",
                                _location=Location(column=5, line=22),
                                text="the user clicks the login button",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="10",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=23),
                                text='the user should see an error message "<error_message>"',
                                data_table=None,
                                doc_string=None,
                            ),
                        ],
                        tags=[],
                        examples=[
                            ExamplesTable(
                                _location=Location(column=5, line=26),
                                name="",
                                table_header=Row(
                                    _id="11",
                                    _location=Location(column=7, line=27),
                                    cells=[
                                        Cell(
                                            _location=Location(column=9, line=27),
                                            value="username",
                                        ),
                                        Cell(
                                            _location=Location(column=23, line=27),
                                            value="password",
                                        ),
                                        Cell(
                                            _location=Location(column=35, line=27),
                                            value="error_message",
                                        ),
                                    ],
                                ),
                                table_body=[
                                    Row(
                                        _id="12",
                                        _location=Location(column=7, line=28),
                                        cells=[
                                            Cell(
                                                _location=Location(column=9, line=28),
                                                value="invalidUser",
                                            ),
                                            Cell(
                                                _location=Location(column=23, line=28),
                                                value="wrongPass",
                                            ),
                                            Cell(
                                                _location=Location(column=35, line=28),
                                                value="Invalid username or password",
                                            ),
                                        ],
                                    ),
                                    Row(
                                        _id="13",
                                        _location=Location(column=7, line=29),
                                        cells=[
                                            Cell(
                                                _location=Location(column=9, line=29),
                                                value="user123",
                                            ),
                                            Cell(
                                                _location=Location(column=23, line=29),
                                                value="incorrect",
                                            ),
                                            Cell(
                                                _location=Location(column=35, line=29),
                                                value="Invalid username or password",
                                            ),
                                        ],
                                    ),
                                ],
                            )
                        ],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="20",
                        keyword="Scenario",
                        _location=Location(column=3, line=31),
                        name="Login with empty username",
                        description="",
                        steps=[
                            Step(
                                _id="16",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=32),
                                text="the user enters an empty username",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="17",
                                keyword="And",
                                keyword_type="Conjunction",
                                _location=Location(column=5, line=33),
                                text="the user enters a valid password",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="18",
                                keyword="When",
                                keyword_type="Action",
                                _location=Location(column=5, line=34),
                                text="the user clicks the login button",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="19",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=35),
                                text='the user should see an error message "Username cannot be empty"',
                                data_table=None,
                                doc_string=None,
                            ),
                        ],
                        tags=[],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="25",
                        keyword="Scenario",
                        _location=Location(column=3, line=37),
                        name="Login with empty password",
                        description="",
                        steps=[
                            Step(
                                _id="21",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=38),
                                text="the user enters a valid username",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="22",
                                keyword="And",
                                keyword_type="Conjunction",
                                _location=Location(column=5, line=39),
                                text="the user enters an empty password",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="23",
                                keyword="When",
                                keyword_type="Action",
                                _location=Location(column=5, line=40),
                                text="the user clicks the login button",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="24",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=41),
                                text='the user should see an error message "Password cannot be empty"',
                                data_table=None,
                                doc_string=None,
                            ),
                        ],
                        tags=[],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="30",
                        keyword="Scenario",
                        _location=Location(column=3, line=43),
                        name="Login with SQL injection attempt",
                        description="",
                        steps=[
                            Step(
                                _id="26",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=44),
                                text="the user enters \"admin' OR '1'='1\" as username",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="27",
                                keyword="And",
                                keyword_type="Conjunction",
                                _location=Location(column=5, line=45),
                                text='the user enters "password" as password',
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="28",
                                keyword="When",
                                keyword_type="Action",
                                _location=Location(column=5, line=46),
                                text="the user clicks the login button",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="29",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=47),
                                text='the user should see an error message "Invalid username or password"',
                                data_table=None,
                                doc_string=None,
                            ),
                        ],
                        tags=[],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="35",
                        keyword="Scenario",
                        _location=Location(column=3, line=50),
                        name="Login button disabled for empty fields",
                        description="",
                        steps=[
                            Step(
                                _id="31",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=51),
                                text="the user has not entered any username or password",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="32",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=52),
                                text="the login button should be disabled",
                                data_table=None,
                                doc_string=None,
                            ),
                        ],
                        tags=[
                            Tag(_id="33", _location=Location(column=3, line=49), name="@login"),
                            Tag(
                                _id="34",
                                _location=Location(column=10, line=49),
                                name="@critical",
                            ),
                        ],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="39",
                        keyword="Scenario",
                        _location=Location(column=3, line=56),
                        name="Login page loads correctly",
                        description="",
                        steps=[
                            Step(
                                _id="36",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=57),
                                text="the login page is loaded",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="37",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=58),
                                text="the login form should be visible",
                                data_table=None,
                                doc_string=None,
                            ),
                        ],
                        tags=[Tag(_id="38", _location=Location(column=3, line=55), name="@smoke")],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="53",
                        keyword="Scenario",
                        _location=Location(column=3, line=61),
                        name="Login with multiple sets of credentials",
                        description="",
                        steps=[
                            Step(
                                _id="44",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=62),
                                text="the following users are registered:",
                                data_table=DataTable(
                                    _location=Location(column=7, line=63),
                                    rows=[
                                        Row(
                                            _id="40",
                                            _location=Location(column=7, line=63),
                                            cells=[
                                                Cell(_location=Location(column=9, line=63), value="username"),
                                                Cell(_location=Location(column=20, line=63), value="password"),
                                            ],
                                        ),
                                        Row(
                                            _id="41",
                                            _location=Location(column=7, line=64),
                                            cells=[
                                                Cell(_location=Location(column=9, line=64), value="user1"),
                                                Cell(_location=Location(column=20, line=64), value="pass1"),
                                            ],
                                        ),
                                        Row(
                                            _id="42",
                                            _location=Location(column=7, line=65),
                                            cells=[
                                                Cell(_location=Location(column=9, line=65), value="user2"),
                                                Cell(_location=Location(column=20, line=65), value="pass2"),
                                            ],
                                        ),
                                        Row(
                                            _id="43",
                                            _location=Location(column=7, line=66),
                                            cells=[
                                                Cell(_location=Location(column=9, line=66), value="user3"),
                                                Cell(_location=Location(column=20, line=66), value="pass3"),
                                            ],
                                        ),
                                    ],
                                ),
                                doc_string=None,
                            ),
                            Step(
                                _id="48",
                                keyword="When",
                                keyword_type="Action",
                                _location=Location(column=5, line=67),
                                text="the user tries to log in with the following credentials:",
                                data_table=DataTable(
                                    _location=Location(column=7, line=68),
                                    rows=[
                                        Row(
                                            _id="45",
                                            _location=Location(column=7, line=68),
                                            cells=[
                                                Cell(_location=Location(column=9, line=68), value="username"),
                                                Cell(_location=Location(column=20, line=68), value="password"),
                                            ],
                                        ),
                                        Row(
                                            _id="46",
                                            _location=Location(column=7, line=69),
                                            cells=[
                                                Cell(_location=Location(column=9, line=69), value="user1"),
                                                Cell(_location=Location(column=20, line=69), value="pass1"),
                                            ],
                                        ),
                                        Row(
                                            _id="47",
                                            _location=Location(column=7, line=70),
                                            cells=[
                                                Cell(_location=Location(column=9, line=70), value="user2"),
                                                Cell(_location=Location(column=20, line=70), value="wrongPass"),
                                            ],
                                        ),
                                    ],
                                ),
                                doc_string=None,
                            ),
                            Step(
                                _id="52",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=71),
                                text="the login attempts should result in:",
                                data_table=DataTable(
                                    _location=Location(column=7, line=72),
                                    rows=[
                                        Row(
                                            _id="49",
                                            _location=Location(column=7, line=72),
                                            cells=[
                                                Cell(_location=Location(column=9, line=72), value="username"),
                                                Cell(_location=Location(column=20, line=72), value="result"),
                                            ],
                                        ),
                                        Row(
                                            _id="50",
                                            _location=Location(column=7, line=73),
                                            cells=[
                                                Cell(_location=Location(column=9, line=73), value="user1"),
                                                Cell(_location=Location(column=20, line=73), value="success"),
                                            ],
                                        ),
                                        Row(
                                            _id="51",
                                            _location=Location(column=7, line=74),
                                            cells=[
                                                Cell(_location=Location(column=9, line=74), value="user2"),
                                                Cell(_location=Location(column=20, line=74), value="failure"),
                                            ],
                                        ),
                                    ],
                                ),
                                doc_string=None,
                            ),
                        ],
                        tags=[],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=None,
                    scenario=Scenario(
                        _id="57",
                        keyword="Scenario",
                        _location=Location(column=3, line=77),
                        name="Check login error message with detailed explanation",
                        description="",
                        steps=[
                            Step(
                                _id="54",
                                keyword="Given",
                                keyword_type="Context",
                                _location=Location(column=5, line=78),
                                text="the user enters invalid credentials",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="55",
                                keyword="When",
                                keyword_type="Action",
                                _location=Location(column=5, line=79),
                                text="the user clicks the login button",
                                data_table=None,
                                doc_string=None,
                            ),
                            Step(
                                _id="56",
                                keyword="Then",
                                keyword_type="Outcome",
                                _location=Location(column=5, line=80),
                                text="the user should see the following error message:",
                                data_table=None,
                                doc_string=DocString(
                                    content="Your login attempt was unsuccessful.\nPlease check your username and password and try again.\nIf the problem persists, contact support.",
                                    delimiter='"""',
                                    _location=Location(column=7, line=81),
                                ),
                            ),
                        ],
                        tags=[],
                        examples=[],
                    ),
                ),
                Child(
                    background=None,
                    rule=Rule(
                        _id="64",
                        keyword="Rule",
                        _location=Location(column=3, line=88),
                        name="a sale cannot happen if there is no stock",
                        description="",
                        tags=[
                            Tag(
                                _id="63",
                                _location=Location(column=3, line=87),
                                name="@some-tag",
                            )
                        ],
                        children=[
                            Child(
                                background=None,
                                rule=None,
                                scenario=Scenario(
                                    _id="62",
                                    keyword="Example",
                                    _location=Location(column=3, line=90),
                                    name="No chocolates left",
                                    description="",
                                    steps=[
                                        Step(
                                            _id="58",
                                            keyword="Given",
                                            keyword_type="Context",
                                            _location=Location(column=5, line=91),
                                            text="the customer has 100 cents",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="59",
                                            keyword="And",
                                            keyword_type="Conjunction",
                                            _location=Location(column=5, line=92),
                                            text="there are no chocolate bars in stock",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="60",
                                            keyword="When",
                                            keyword_type="Action",
                                            _location=Location(column=5, line=93),
                                            text="the customer tries to buy a 1 cent chocolate bar",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="61",
                                            keyword="Then",
                                            keyword_type="Outcome",
                                            _location=Location(column=5, line=94),
                                            text="the sale should not happen",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                    ],
                                    tags=[],
                                    examples=[],
                                ),
                            )
                        ],
                    ),
                    scenario=None,
                ),
                Child(
                    background=None,
                    rule=Rule(
                        _id="75",
                        keyword="Rule",
                        _location=Location(column=3, line=96),
                        name="A sale cannot happen if the customer does not have enough money",
                        description="",
                        tags=[],
                        children=[
                            Child(
                                background=None,
                                rule=None,
                                scenario=Scenario(
                                    _id="69",
                                    keyword="Example",
                                    _location=Location(column=5, line=98),
                                    name="Not enough money",
                                    description="",
                                    steps=[
                                        Step(
                                            _id="65",
                                            keyword="Given",
                                            keyword_type="Context",
                                            _location=Location(column=7, line=99),
                                            text="the customer has 100 cents",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="66",
                                            keyword="And",
                                            keyword_type="Conjunction",
                                            _location=Location(column=7, line=100),
                                            text="there are chocolate bars in stock",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="67",
                                            keyword="When",
                                            keyword_type="Action",
                                            _location=Location(column=7, line=101),
                                            text="the customer tries to buy a 125 cent chocolate bar",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="68",
                                            keyword="Then",
                                            keyword_type="Outcome",
                                            _location=Location(column=7, line=102),
                                            text="the sale should not happen",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                    ],
                                    tags=[],
                                    examples=[],
                                ),
                            ),
                            Child(
                                background=None,
                                rule=None,
                                scenario=Scenario(
                                    _id="74",
                                    keyword="Example",
                                    _location=Location(column=5, line=105),
                                    name="Enough money",
                                    description="",
                                    steps=[
                                        Step(
                                            _id="70",
                                            keyword="Given",
                                            keyword_type="Context",
                                            _location=Location(column=7, line=106),
                                            text="the customer has 100 cents",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="71",
                                            keyword="And",
                                            keyword_type="Conjunction",
                                            _location=Location(column=7, line=107),
                                            text="there are chocolate bars in stock",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="72",
                                            keyword="When",
                                            keyword_type="Action",
                                            _location=Location(column=7, line=108),
                                            text="the customer tries to buy a 75 cent chocolate bar",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                        Step(
                                            _id="73",
                                            keyword="Then",
                                            keyword_type="Outcome",
                                            _location=Location(column=7, line=109),
                                            text="the sale should happen",
                                            data_table=None,
                                            doc_string=None,
                                        ),
                                    ],
                                    tags=[],
                                    examples=[],
                                ),
                            ),
                        ],
                    ),
                    scenario=None,
                ),
            ],
        ),
        comments=[
            Comment(_location=Location(column=1, line=1), text="# This is a comment"),
            Comment(
                _location=Location(column=1, line=9),
                text="    # Background steps run before each scenario",
            ),
            Comment(_location=Location(column=1, line=12), text="    # Scenario within the rule"),
            Comment(
                _location=Location(column=1, line=25),
                text="      # Examples table provides data for the scenario outline",
            ),
            Comment(
                _location=Location(column=1, line=54),
                text="  # Tags can be used to categorize scenarios",
            ),
            Comment(
                _location=Location(column=1, line=60),
                text="  # Using Data Tables for more complex data",
            ),
            Comment(
                _location=Location(column=1, line=76),
                text="  # Using Doc Strings for multi-line text",
            ),
            Comment(_location=Location(column=1, line=89), text="  # Unhappy path"),
            Comment(_location=Location(column=1, line=97), text="    # Unhappy path"),
            Comment(_location=Location(column=1, line=104), text="    # Happy path"),
        ],
    )

    assert gherkin_doc == expected_document
