"""Test code generation command."""

from __future__ import annotations

import os
import sys
import textwrap

from pytest_bdd.scripts import main

PATH = os.path.dirname(__file__)


def test_generate(pytester, monkeypatch, capsys):
    """Test if the code is generated by a given feature."""

    features = pytester.mkdir("scripts")
    feature = features.joinpath("generate.feature")
    feature.write_text(
        textwrap.dedent(
            """\
            Feature: Code generation

                Scenario: Given and when using the same fixture should not evaluate it twice
                    Given I have an empty list
                    And 1 have a fixture (appends 1 to a list) in reuse syntax

                    When I use this fixture

                    Then my list should be [1]
            """
        ),
        "utf-8",
    )

    monkeypatch.setattr(sys, "argv", ["", "generate", str(feature)])
    main()
    out, err = capsys.readouterr()
    assert out == textwrap.dedent(
        '''\
    """Code generation feature tests."""

    from pytest_bdd import (
        given,
        scenarios,
        then,
        when,
    )

    scenarios('scripts/generate.feature')


    @given('1 have a fixture (appends 1 to a list) in reuse syntax')
    def _():
        """1 have a fixture (appends 1 to a list) in reuse syntax."""
        raise NotImplementedError


    @given('I have an empty list')
    def _():
        """I have an empty list."""
        raise NotImplementedError


    @when('I use this fixture')
    def _():
        """I use this fixture."""
        raise NotImplementedError


    @then('my list should be [1]')
    def _():
        """my list should be [1]."""
        raise NotImplementedError

    '''
    )


def test_generate_with_quotes(pytester):
    """Test that code generation escapes quote characters properly."""
    pytester.makefile(
        ".feature",
        generate_with_quotes=textwrap.dedent(
            '''\
        Feature: Handling quotes in code generation

            Scenario: A step definition with quotes should be escaped as needed
                Given I have a fixture with 'single' quotes
                And I have a fixture with "double" quotes
                And I have a fixture with single-quote \'\'\'triple\'\'\' quotes
                And I have a fixture with double-quote """triple""" quotes

                When I generate the code

                Then The generated string should be written
        '''
        ),
    )

    result = pytester.run("pytest-bdd", "generate", "generate_with_quotes.feature")
    assert str(result.stdout) == textwrap.dedent(
        '''\
    """Handling quotes in code generation feature tests."""

    from pytest_bdd import (
        given,
        scenarios,
        then,
        when,
    )

    scenarios('generate_with_quotes.feature')


    @given('I have a fixture with "double" quotes')
    def _():
        """I have a fixture with "double" quotes."""
        raise NotImplementedError


    @given('I have a fixture with \\'single\\' quotes')
    def _():
        """I have a fixture with 'single' quotes."""
        raise NotImplementedError


    @given('I have a fixture with double-quote """triple""" quotes')
    def _():
        """I have a fixture with double-quote \\"\\"\\"triple\\"\\"\\" quotes."""
        raise NotImplementedError


    @given('I have a fixture with single-quote \\'\\'\\'triple\\'\\'\\' quotes')
    def _():
        """I have a fixture with single-quote \'\'\'triple\'\'\' quotes."""
        raise NotImplementedError


    @when('I generate the code')
    def _():
        """I generate the code."""
        raise NotImplementedError


    @then('The generated string should be written')
    def _():
        """The generated string should be written."""
        raise NotImplementedError
    '''
    )


def test_generate_is_idempotent(pytester):
    """Test that invoking the generation script twice yields the same output.

    Also make sure that applying the generated code twice to the same module
    does not duplicate tests, since scenarios() skips already bound scenarios.
    """
    pytester.makefile(
        ".feature",
        idempotency=textwrap.dedent(
            """\
            Feature: Idempotent code generation

                Scenario: First scenario
                    Given I have a step

                Scenario: Second scenario
                    Given I have a step
            """
        ),
    )

    first = pytester.run("pytest-bdd", "generate", "idempotency.feature")
    second = pytester.run("pytest-bdd", "generate", "idempotency.feature")
    assert str(first.stdout) == str(second.stdout)

    pytester.makepyfile(str(first.stdout) + "\n\nscenarios('idempotency.feature')\n")
    result = pytester.runpytest("--collect-only", "-q")
    collected = [line for line in result.stdout.lines if "::test_" in line]
    assert len(collected) == 2


def test_unicode_characters(pytester, monkeypatch):
    """Test generating code with unicode characters.

    Primary purpose is to ensure compatibility with Python2.
    """

    pytester.makefile(
        ".feature",
        unicode_characters=textwrap.dedent(
            """\
        Feature: Generating unicode characters

            Scenario: Calculating the circumference of a circle
                Given We have a circle
                When We want to know its circumference
                Then We calculate 2 * ℼ * 𝑟
        """
        ),
    )

    result = pytester.run("pytest-bdd", "generate", "unicode_characters.feature")
    expected_output = textwrap.dedent(
        '''\
            """Generating unicode characters feature tests."""

            from pytest_bdd import (
                given,
                scenarios,
                then,
                when,
            )

            scenarios('unicode_characters.feature')


            @given('We have a circle')
            def _():
                """We have a circle."""
                raise NotImplementedError


            @when('We want to know its circumference')
            def _():
                """We want to know its circumference."""
                raise NotImplementedError


            @then('We calculate 2 * ℼ * 𝑟')
            def _():
                """We calculate 2 * ℼ * 𝑟."""
                raise NotImplementedError
            '''
    )
    assert str(result.stdout) == expected_output
